---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: bento/ubuntu-16.04 

suites:
  - name: node
#    environments_path: ../../environments
#    cookbooks_path: ..
    run_list:
      - recipe[precision]
